#!/usr/bin/env python3
"""
HuggingClaw Cloudflare Proxy Setup
Deploys a Cloudflare Worker that proxies blocked outbound traffic (Telegram, Discord, etc.)
from HF Spaces through a Cloudflare Worker.
"""

import json
import os
import re
import secrets
import sys
import urllib.error
import urllib.request
from pathlib import Path

API_BASE = "https://api.cloudflare.com/client/v4"
ENV_FILE = Path("/tmp/huggingclaw-cloudflare-proxy.env")

DEFAULT_ALLOWED = [
    "api.telegram.org",
    "discord.com", "discordapp.com", "gateway.discord.gg", "status.discord.com",
    "web.whatsapp.com",
    "graph.facebook.com", "graph.instagram.com",
    "api.twitter.com", "api.x.com", "upload.twitter.com",
    "api.linkedin.com", "www.linkedin.com",
    "open.tiktokapis.com", "oauth.reddit.com",
    "youtube.com", "www.youtube.com",
    "api.resend.com", "api.sendgrid.com", "api.mailgun.net",
    "googleapis.com", "google.com", "googleusercontent.com", "gstatic.com",
]


def cf_request(method, path, token, body=None, content_type="application/json"):
    req = urllib.request.Request(
        f"{API_BASE}{path}",
        data=body,
        method=method,
        headers={"Authorization": f"Bearer {token}", "Content-Type": content_type},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            payload = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        raise e
    if not payload.get("success"):
        errors = payload.get("errors") or [{"message": "Unknown CF API error"}]
        raise RuntimeError(errors[0].get("message", "Unknown CF API error"))
    return payload["result"]


def cf_upload_worker(account_id, worker_name, token, script_source):
    """
    Upload Worker script via multipart/form-data.
    The metadata part declares this as an ES module (main_module).
    The script part must use 'export default' syntax to match.
    """
    boundary = "HuggingClawBoundary1337"
    metadata = json.dumps({
        "main_module": "worker.js",
        "bindings": [],
        "compatibility_date": "2024-09-23",
        "usage_model": "bundled",
    })

    parts = []
    # Part 1: metadata
    parts.append(f"--{boundary}\r\n".encode())
    parts.append(b'Content-Disposition: form-data; name="metadata"\r\n')
    parts.append(b"Content-Type: application/json\r\n\r\n")
    parts.append(metadata.encode())
    parts.append(b"\r\n")
    # Part 2: script
    parts.append(f"--{boundary}\r\n".encode())
    parts.append(b'Content-Disposition: form-data; name="worker.js"; filename="worker.js"\r\n')
    parts.append(b"Content-Type: application/javascript+module\r\n\r\n")
    parts.append(script_source.encode())
    parts.append(b"\r\n")
    parts.append(f"--{boundary}--\r\n".encode())

    body = b"".join(parts)
    req = urllib.request.Request(
        f"{API_BASE}/accounts/{account_id}/workers/scripts/{worker_name}",
        data=body,
        method="PUT",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            payload = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        raise RuntimeError(f"Worker upload failed HTTP {e.code}: {detail}")
    if not payload.get("success"):
        errors = payload.get("errors") or [{"message": "Unknown CF API error"}]
        raise RuntimeError(f"Worker upload error: {errors[0].get('message')}")


def render_worker(secret_value, allowed_targets, allow_proxy_all):
    """
    Generates an ES module Cloudflare Worker script.
    MUST use 'export default' — no addEventListener (that's Service Worker format,
    which is rejected when metadata declares main_module / ES module format).
    """
    allowed_json = json.dumps(allowed_targets)
    allow_all_js = "true" if allow_proxy_all else "false"
    secret_json = json.dumps(secret_value)

    return f"""\
// HuggingClaw Cloudflare Proxy Worker — ES Module format
// Auto-generated by cloudflare-proxy-setup.py

const PROXY_SHARED_SECRET = {secret_json};
const ALLOW_PROXY_ALL = {allow_all_js};
const ALLOWED_TARGETS = {allowed_json};

function isAllowedHost(hostname) {{
  const h = String(hostname || "").trim().toLowerCase();
  if (!h) return false;
  // Never proxy private/loopback ranges
  if (/^(localhost|127\\.\\d+\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|192\\.168\\.\\d+\\.\\d+)$/.test(h)) return false;
  if (/^172\\.(1[6-9]|2[0-9]|3[01])\\.\\d+\\.\\d+$/.test(h)) return false;
  if (ALLOW_PROXY_ALL) return true;
  return ALLOWED_TARGETS.some(d => h === d || h.endsWith("." + d));
}}

async function handleRequest(request) {{
  const url = new URL(request.url);
  const targetHost = request.headers.get("x-target-host") || url.searchParams.get("proxy_target");

  if (PROXY_SHARED_SECRET) {{
    const key = request.headers.get("x-proxy-key") || url.searchParams.get("proxy_key") || "";
    if (key !== PROXY_SHARED_SECRET) {{
      // Allow bare Telegram bot paths without a key (legacy compat)
      if (!(url.pathname.startsWith("/bot") && !targetHost)) {{
        return new Response("Unauthorized", {{ status: 401 }});
      }}
    }}
  }}

  let targetBase;
  if (targetHost) {{
    if (!isAllowedHost(targetHost)) {{
      return new Response(`Forbidden: ${{targetHost}} not in allowlist`, {{ status: 403 }});
    }}
    targetBase = "https://" + targetHost;
  }} else if (url.pathname.startsWith("/bot")) {{
    targetBase = "https://api.telegram.org";
  }} else {{
    return new Response("Bad request: no target host", {{ status: 400 }});
  }}

  const qs = new URLSearchParams(url.search);
  qs.delete("proxy_target");
  qs.delete("proxy_key");
  const qstr = qs.toString();
  const targetUrl = targetBase + url.pathname + (qstr ? "?" + qstr : "");

  const headers = new Headers(request.headers);
  ["cf-connecting-ip","cf-ray","cf-visitor","host","x-real-ip","x-target-host","x-proxy-key"]
    .forEach(h => headers.delete(h));

  try {{
    return await fetch(new Request(targetUrl, {{
      method: request.method,
      headers,
      body: request.body,
      redirect: "follow",
    }}));
  }} catch (err) {{
    return new Response("Proxy error: " + err.message, {{ status: 502 }});
  }}
}}

export default {{
  async fetch(request, env, ctx) {{
    return handleRequest(request);
  }}
}};
"""


def slugify(value):
    cleaned = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    cleaned = re.sub(r"-{2,}", "-", cleaned)
    return (cleaned or "huggingclaw-proxy")[:63].rstrip("-")


def derive_worker_name():
    explicit = os.environ.get("CLOUDFLARE_WORKER_NAME", "").strip()
    if explicit:
        return slugify(explicit)
    space_host = os.environ.get("SPACE_HOST", "").strip()
    if space_host:
        return slugify(space_host.replace(".hf.space", "") + "-proxy")
    return "huggingclaw-proxy"


def write_env(proxy_url, proxy_secret):
    ENV_FILE.write_text(
        f'export CLOUDFLARE_PROXY_URL="{proxy_url}"\n'
        f'export CLOUDFLARE_PROXY_SECRET="{proxy_secret}"\n',
        encoding="utf-8",
    )
    try:
        ENV_FILE.chmod(0o600)
    except OSError:
        pass


def main():
    existing_url = os.environ.get("CLOUDFLARE_PROXY_URL", "").strip()
    existing_secret = os.environ.get("CLOUDFLARE_PROXY_SECRET", "").strip()
    api_token = os.environ.get("CLOUDFLARE_WORKERS_TOKEN", "").strip()

    if existing_url:
        write_env(existing_url, existing_secret)
        if not existing_secret:
            print("Warning: CLOUDFLARE_PROXY_URL set but CLOUDFLARE_PROXY_SECRET empty.", file=sys.stderr)
        return 0

    if not api_token:
        return 0

    account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "").strip()
    try:
        if not account_id:
            accounts = cf_request("GET", "/accounts", api_token)
            if not accounts:
                raise RuntimeError("No Cloudflare accounts found for this token.")
            account_id = accounts[0]["id"]

        subdomain_info = cf_request("GET", f"/accounts/{account_id}/workers/subdomain", api_token)
        subdomain = (subdomain_info or {}).get("subdomain", "").strip()
        if not subdomain:
            raise RuntimeError("Workers subdomain not configured. Enable workers.dev in Cloudflare dashboard.")

        worker_name = derive_worker_name()
        allowed_raw = os.environ.get("CLOUDFLARE_PROXY_DOMAINS", "").strip()
        allow_proxy_all = allowed_raw == "*"
        if allow_proxy_all:
            allowed_targets = list(DEFAULT_ALLOWED)
        else:
            extra = [v.strip() for v in allowed_raw.split(",") if v.strip()]
            seen = set(DEFAULT_ALLOWED)
            allowed_targets = list(DEFAULT_ALLOWED)
            for d in extra:
                if d not in seen:
                    allowed_targets.append(d)
                    seen.add(d)

        proxy_secret = existing_secret or secrets.token_urlsafe(24)
        worker_source = render_worker(proxy_secret, allowed_targets, allow_proxy_all)

        cf_upload_worker(account_id, worker_name, api_token, worker_source)

        cf_request(
            "POST",
            f"/accounts/{account_id}/workers/scripts/{worker_name}/subdomain",
            api_token,
            body=json.dumps({"enabled": True, "previews_enabled": True}).encode(),
        )

        proxy_url = f"https://{worker_name}.{subdomain}.workers.dev"
        write_env(proxy_url, proxy_secret)
        print(f"Cloudflare proxy worker deployed: {proxy_url}")
        return 0

    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        print(f"Cloudflare proxy setup failed: HTTP {e.code} {detail}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Cloudflare proxy setup failed: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
